<a href="https://colab.research.google.com/github/mirsazzathossain/CSE317-Lab/blob/main/Lab_3_K_Means_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1. Import necessary packages:**

In [2]:
import numpy as np
import pandas as pd


#### **2. Upload and load dataset:**
At first we have to upload the dataset to google colab to start working with it. Please download the **"bookprice.csv"** dataset from piazza resourse or [click here](https://github.com/mirsazzathossain/CSE317-Lab/blob/12e1c96ad071eda5912c2ba2597e110bb709c680/bookprice.csv) to download it. Then click on files form sidebar, drag and drop your file to side bar to upload the dataset.

Now, use `data = pd.read_csv("bookprice.csv")` to load the data.

In [5]:
data = pd.read_csv("bookprice.csv")
data = data.to_numpy()
print(data)

[[166  54]
 [195  82]
 [200  72]
 [260  72]
 [265  90]
 [335 124]
 [370  94]
 [450 118]
 [517 152]
 [552 132]]


#### **3. Get the size of data.:**
Get the size of `data` using `np.shape(data)`. This will return a tuple consists of number of rows and columns of `data`. Save these into two varible named `row` and `col`.

In [6]:
row, col = np.shape(data)
print(row, col)

10 2


#### **4. Plot 2D data. X-axis show page, Y-Axis shows price**
Draw a scatter plot using `plt.scatter()`. Keep page in x-axis and price in y-axis. Show xlabel and ylabel using `plt.xlabel('Page')` and `plt.ylabel('Price')`. Put limit of the axis using `plt.xlim(150, 600)` and `plt.ylim(50, 160)`

#### **5. Decide number of groups:**
Let's take number of group `k = 3`

In [7]:
k=3

#### **6. Take a initial zero matrix called centroids:**
For three group we need three initial centroid. Initially we will take the origin (0, 0) as centroid. Use `np.zeros()` to generate the centroid matrix. 

**Note:** The size of the centroid matrix will be (k, col)

In [10]:
centroids = np.zeros((k, col))
print(centroids)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### **7. Generate random indices ranges from 1 to number of rows of data:**
Use `np.random.permutation(row)` to generate random indices and store in randidx.

In [11]:
randidx = np.random.permutation(row)
print(randidx)

[5 9 7 1 0 8 4 6 3 2]


#### **8. Copy the data from first k (random) indices from data:**
Use first k indices from randomly generated indices to get the  specific data from `data` and make these specific data as new centroids.

In [16]:
for i in range(k):
  centroids[i] = data[randidx[i]]

print(centroids)

[[335. 124.]
 [552. 132.]
 [450. 118.]]


#### **9. Create empty array named group:**
Create a empty array named group to keep the group number that corresponds to each datapoint.

In [22]:
group = np.zeros(row)-1
print(group)

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


#### **10. Calculate distance of each point from each centroid and assign the point to a specific centroid which is closest to the point:**

1.   Loop over all datapoint one by one.
2.   For each datapoint calculate distances of $i^{th}$ point $(data[i,:])$ from centroids[0], then centroids[1], and then centroids[2]
3.   Find out which centroid is the closest to the point $data[i,:]$
3.   Save the centroid no that is closest to the datapoint in specific index of group. 

     E.g. If $i^{th}$ datapoint is closer to centroid[0] then `group[i] = 0`
4.   Calculate the average of each group that will be new centroid.

     *Note: You can use `pd.DataFrame(data).groupby(by=group)` to get k distinct group and then take average using `.mean()`. You will get an dataframe object as result, to get numpy array use `.values`


In [ ]:
# Write appropriate code

#### **11. Plot the centroids with different marker. Say ‘d’ for diamond:**
Use different marker by simply passing an extra parameter to `plt.scatter()` function. E.g. `plt.scatter(--, --, marker='d')`

In [ ]:
# Write appropriate code